marcos-jaramillo/Alliax

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/controller/BuscarClasePedidoConfig.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/controller/BuscarClasePedidoRFC.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/controller/BuscarDestinatariosMercanciasConfig.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/controller/BuscarDestinatariosMercanciasRFC.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/controller/BuscarMetodoPagoCfdiConfig.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/controller/BuscarMetodoPagoCfdiRFC.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/controller/UsoCfdiConfig.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/controller/UsoCfdiRFC.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/model/ClasePedido.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/model/DestinatarioMercancia.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/model/MetodoPagoCFDI.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/model/UsoCFDI.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/model/UsoCFDIDetalle.java
BuscarDestinatariosMercanciasRFC
BuscarClasePedidoRFC
BuscarMetodoPagoCfdiRFC
UsoCfdiRFC
=> nuevos RFC

PortalClientesRotoplas/src/main/webapp/contactanos.xhtml, PortalClientesRotoplas/src/main/webapp/estadoCuenta.xhtml, PortalClientesRotoplas/src/main/webapp/index.xhtml, PortalClientesRotoplas/src/main/webapp/pedidos/listado.xhtml, PortalClientesRotoplas/src/main/webapp/recuperaPassword_bak.xhtml, PortalClientesRotoplas/src/main/webapp/resources/lookAndFeel/css/estilos.css, PortalClientesRotoplas/src/main/webapp/resources/lookAndFeel/js/tabla.js, PortalClientesRotoplas/src/main/webapp/templateBoot.xhtml
Se justo el template junto con al estilo.css para mostrar botones, se anexa avance de pedidos/listado, para empezar pruebas en SAP
=> correccion acceso y botnos

PortalClientesRotoplas/src/main/webapp/indexPwdChange_bak.xhtml, PortalClientesRotoplas/src/main/webapp/pedidos/listado.xhtml, PortalClientesRotoplas/src/main/webapp/resources/lookAndFeel/js/tabla.js, PortalClientesRotoplas/src/main/webapp/templateBoot.xhtml
Correccion sobre templateBoot.xhtml, pedido/listado.xhtml.
Se agrega el combiar contraseña indexPwdChange.xhtml, se ajusta tabla.js para funcion con listado.xhtml
=> Cambios en pedido/listado

PortalClientesRotoplas/src/main/webapp/pedidos/listado.xhtml, PortalClientesRotoplas/src/main/webapp/templateBoot.xhtml
Se realiza correccion en vista misPedidos para pruebas SAP
Se quita link Mi cuenta del submenu usuario
=> Correccion pedidos/listado

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/locale/Labels_es.properties, PortalClientesRotoplas/src/main/webapp/pedidos/listado.xhtml
=> Botones cancelar y copiar pedido

PortalClientesRotoplas/src/main/webapp/estadoCuenta.xhtml, PortalClientesRotoplas/src/main/webapp/resources/lookAndFeel/js/tabla.js
=> Modificaciones a estadoCuenta.xhtml

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/general/formato/Fecha.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/EstadoCuenta_backing.java, PortalClientesRotoplas/src/main/webapp/estadoCuenta.xhtml, PortalClientesRotoplas/src/main/webapp/resources/lookAndFeel/css/estilos.css, PortalClientesRotoplas/src/main/webapp/resources/lookAndFeel/js/tabla.js
Modificaciones al componente estadoCuenta
=> Modificaciones al componente estadoCuenta

PortalClientesRotoplas/src/main/webapp/consultaExistencia.xhtml, PortalClientesRotoplas/src/main/webapp/resources/lookAndFeel/js/consultaExistencias.js
=> pulllllllllllllllllllllllll

DB/Pedidos/pedidoPartidasNewColumns_1.sql, DB/Pedidos/pedidonewColumn_1.sql, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/domain/Pedido.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/domain/PedidoPartidas.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/locale/Labels_es.properties, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/model/CotizacionFlete.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/model/DetallePedidoCotizacion.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/service/PedidoPartidasService.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/service/jpa/PedidoPartidasServiceImpl.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/service/jpa/PedidoServiceImpl.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ConsultaCotizacion_backing.java, PortalClientesRotoplas/src/main/webapp/cotizaciones.xhtml
van 2 scrips para agregar campos a la DB , hay que ejecutarlos
=> commit pantallas cotizaciones

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/service/PedidoService.java
=> Cotizaciones - service faltante

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/EstadoCuenta_backing.java
Modificaciones de fecha EstadoCuenta_backing
=> Modificaciones de fecha EstadoCuenta_backing

PortalClientesRotoplas/src/main/webapp/estadoCuenta.xhtml
Modificaciones PDF estadoCuenta.xhtml
=> Modificaciones PDF estadoCuenta.xhtml

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/AltaColaboradores_backing.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/RecuperaPwd_backing.java, PortalClientesRotoplas/src/main/webapp/altaColaboradores.xhtml, PortalClientesRotoplas/src/main/webapp/recuperaPassword.xhtml, PortalClientesRotoplas/src/main/webapp/resources/lookAndFeel/js/altaColaboradores.js, PortalClientesRotoplas/src/main/webapp/resources/lookAndFeel/js/consultaExistencias.js
=> fix alta Colaboradores

PortalClientesRotoplas/src/main/webapp/cotizaciones.xhtml
=> Cotizacion paginado Detalles

PortalClientesRotoplas/src/main/webapp/pedidos/listado.xhtml
=> listado facturas

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ListadoPedidos_backing.java, PortalClientesRotoplas/src/main/webapp/pedidos/listado.xhtml
Modificacion de ListadoPedidos estado
=> Modificacion de ListadoPedidos estado 

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/controller/ListaPedidosRFC.java
=> Log modificaciones listaPedidosRFC

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/AltaColaboradores_backing.java
=> FIX ALTA COLABORADOR CORREO

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/controller/DetallePedidoRFC.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/model/Item.java, PortalClientesRotoplas/src/main/webapp/pedidos/listado.xhtml, PortalClientesRotoplas/src/main/webapp/resources/lookAndFeel/css/estilos.css
Modificaciones Pedidos listado.xhtml
=> Modificaciones Pedidos listado.xhtml

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ConsultaExistencias_backing.java, PortalClientesRotoplas/src/main/webapp/consultaExistencia.xhtml
=> fix consulta Existencia

PortalClientesRotoplas/src/main/webapp/index.xhtml
Se agregaron las funciones con los contenidos de los casos que maneja el login
=> avance notificaciones login

PortalClientesRotoplas/src/main/webapp/pedidos/listado.xhtml
=> se remueve el estatus CANC

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/controller/ListaPedidosRFC.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/model/OrdenVenta.java
Reverts marcos-jaramillo/Alliax#93
=> Revert "nuevo campo segmento desde el rfc de pedidos"

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/general/formato/Fecha.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ListadoPedidos_backing.java, PortalClientesRotoplas/src/main/webapp/pedidos/listado.xhtml
Fix para consulta de fecha, mis pedidos
=> Fix para consulta de fecha, mis pedidos

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/AltaMateriales_backing.java, PortalClientesRotoplas/src/main/webapp/admin/altaMateriales.xhtml, PortalClientesRotoplas/src/main/webapp/resources/lookAndFeel/js/altaColaboradores.js, PortalClientesRotoplas/src/main/webapp/resources/lookAndFeel/js/altaMateriales.js
=> cambios pantalla altaMaterial

PortalClientesRotoplas/src/main/webapp/templateBoot.xhtml
marca mis pedidos al estar en crearPedido
=> ajuste panel de navegacion marcado mis pedidos

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/util/Helper.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ManageLogin.java, PortalClientesRotoplas/src/main/java/com/portalclientes/spring/security/ChangePasswordFilter.java, PortalClientesRotoplas/src/main/java/com/portalclientes/spring/security/MyAuthenticationFailureListener.java, PortalClientesRotoplas/src/main/webapp/index.xhtml
=> actualizacion notificaicon login

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/CrearPedido_backing.java, PortalClientesRotoplas/src/main/webapp/pedidos/listado.xhtml
=> Envio de pedido al generarse

PortalClientesRotoplas/src/main/webapp/pedidos/listado.xhtml
Envio de numero de pedido a mis pedidos
=> Envio de numero de pedido a mis pedidos

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ConsultaCotizacion_backing.java, PortalClientesRotoplas/src/main/webapp/cotizaciones.xhtml
actualizacion de pantalla y agregar monto y estado de cotizacion
=> cotizaciones actualizacion

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ConsultaCotizacion_backing.java, PortalClientesRotoplas/src/main/webapp/cotizaciones.xhtml
=> cotizaciones muestra boton

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ConsultaCotizacion_backing.java, PortalClientesRotoplas/src/main/webapp/cotizaciones.xhtml
=> cotizacion ordenar pedido

PortalClientesRotoplas/src/main/webapp/estadoCuenta.xhtml, PortalClientesRotoplas/src/main/webapp/resources/lookAndFeel/js/tabla.js
Modificaciones estadoCuenta al role ROLE_VENTAS_MEMBER
=> Modificaciones estadoCuenta al role ROLE_VENTAS_MEMBER

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ConsultaCotizacion_backing.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/CrearPedido_backing.java, PortalClientesRotoplas/src/main/webapp/pedidos/listado.xhtml
Envio de mensaje para pedidos creados
=> Envio de mensaje para pedidos creados

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ConsultaCotizacion_backing.java
=> cotizaciones  motivo pedido

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ConsultaCotizacion_backing.java
=> cotizacion

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ConsultaCotizacion_backing.java
=> cotizaciones moneda

PortalClientesRotoplas/src/main/webapp/cotizaciones.xhtml
=> cotizacion numero pedido

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/velocity/templates/envioCotizacion.vm, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ConsultaCotizacion_backing.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ListadoPedidos_backing.java
Filtro de consulta de pedido generado
=> Filtro de consulta de pedido generado

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/model/CotizacionFlete.java
=> cotizaciones cambio unidad

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/controller/CrearPedidoRFC.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/model/PedidoPartidas.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ConsultaCotizacion_backing.java
=> cotizaciones monto flete

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/controller/CrearPedidoRFC.java
=> cotizaciones validacion sku

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/controller/ConstructEmail.java
=> envio de email de cotizacion

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/general/formato/Fecha.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/velocity/templates/envioCotizacion.vm, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ConsultaCotizacion_backing.java
Envio de mail de cotizacion ajustes
=> Envio de mail de cotizacion ajustes

PortalClientesRotoplas/src/main/webapp/pedidos/listado.xhtml
Envio de mensaje exitoso en generacion de pedidos
=> Envio de mensaje exitoso en generacion de pedidos

PortalClientesRotoplas/src/main/webapp/estadoCuenta.xhtml, PortalClientesRotoplas/src/main/webapp/resources/lookAndFeel/js/tabla.js
Modificaciones estadoCuenta vendedor
=> Modificaciones estadoCuenta vendedor

PortalClientesRotoplas/src/main/webapp/cotizaciones.xhtml
selector de fecha mayor a la actual
=> cotizaciones fecha

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/AltaMateriales_backing.java
=> logs alta material

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ListadoPedidos_backing.java, PortalClientesRotoplas/src/main/webapp/pedidos/listado.xhtml
=> Pedidos detalle Facturas

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ConsultaCotizacion_backing.java
Ajusten en envio de email de cotizacion
=> Ajusten en envio de email de cotizacion

PortalClientesRotoplas/src/main/webapp/estadoCuenta.xhtml, PortalClientesRotoplas/src/main/webapp/resources/lookAndFeel/js/tabla.js
Mensaje de notificación para noCliente vendedor
=> Mensaje de notificación para noCliente vendedor

PortalClientesRotoplas/src/main/webapp/cotizaciones.xhtml
cotizaciones fecha en explorer
=> cotizaciones fecha en explorer

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ConsultaCotizacion_backing.java
Envio de correo para cotizaciones
=> Envio de correo para cotizaciones

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ListadoPedidos_backing.java
detalle facturas numero Documento
=> detalle facturas

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ConsultaExistencias_backing.java, PortalClientesRotoplas/src/main/webapp/consultaExistencia.xhtml, PortalClientesRotoplas/src/main/webapp/pedidos/listado.xhtml, PortalClientesRotoplas/src/main/webapp/resources/lookAndFeel/js/consultaExistencias.js
funcionalidad nueva ConsultaExistencia
=> funcionalidad nueva ConsultaExistencia

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ConsultaCotizacion_backing.java
=> Envio de mail de cotizaciones

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/model/CotizacionFlete.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/model/DetallePedidoCotizacion.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ConsultaCotizacion_backing.java, PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/view/ListadoPedidos_backing.java, PortalClientesRotoplas/src/main/webapp/cotizaciones.xhtml
=> cotizaciones formato 

PortalClientesRotoplas/src/main/webapp/contactanos.xhtml, PortalClientesRotoplas/src/main/webapp/resources/lookAndFeel/js/tabla.js
fix estadoCuenta tabla refresca
=> fix estadoCuenta tabla refresca

PortalClientesRotoplas/src/main/java/com/alliax/portalclientes/velocity/templates/envioCotizacion.vm
=> Envio de correo de cotizacion
